version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/diary-app main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run cmd/main.go

    swagger.gen:
        desc: Generate Go code
        cmds:
        - GOFLAGS=-mod=mod go generate github.com/zalynskaya/diary-app/cmd github.com/zalynskaya/diary-app/cmd/pkg/swagger

    swagger.validate:
        desc: Validate swagger
        cmds:
        - swagger validate swagger.yml

    swagger.doc:
        desc: Doc for swagger
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < swagger.yml > index.html